// Black Unicorn Wallpapers by Alexander Abraham, The Black Unicorn.
// Licensed under the MIT license.

import 'package:dio/dio.dart';
import 'package:flutter/material.dart';
import 'package:termstyle/termstyle.dart';

Dio dio = new Dio();
String appTitle = 'BUWA';
String appVersion = '1.3.0';
String unicorn = getEmoji('unicornHead');
String redHeart = getEmoji('redHeart');
String wallpapersAPI = 'https://blckunicorn.art/assets/buwa/stable/api/wallpapers.json';
String appAuthor = 'TBU $unicorn$redHeart';
String logoPath = 'assets/images/logo.png';
String authorTwitterHandle = '@blvckuncrn';
String appLicense = 'MIT';
Color mainColor = Color(0xFFFFFFFF);
Color accentColor = Color(0xFF000000);
String defaultFont = 'ProductSansBold';
String isInstallingDefault = 'Nonus';
double textFontSize = 25;
double animationSize = 150;
double animationSpacing = 250;
double stdElevation = 0;
double stdRounding = 25;
double verticalPadding = 6;
double horizontalPadding = 60;
double boxSpacing = 20;
double specialSpacing = 10;
double specialPadding = 30;
double pictureBoxWidth = 300;
double pictureBoxHeight = 500;
double stdPadding = 10;
double dividerHeight = 1;
double specialPaddingTwo = 6;
double specialRounding = 15;
double infoPadding = 20;
double infoRounding = 25;
double infoPicSize = 250;
double topPadding = 120;
double bottomPadding = 170;
double sidePadding = 70;
double specialBoxSpacing = 60;
double boxSpacer = 50;
double boxWidth = 600;
double boxHeight = 100;
double mySpecialPadding = 30;
double mySpecialRounding = 15;
double logoDimensions = 150;
int loadingDuration = 250;
double myHeadingFontSize = 30;
double mySpecialRoundingOne = 30;
double myHeadingFontSizeOne = 28;
double stdBorderWidth = 4.0;
double myBannerDimensions = 250;
double titleOffSetOne = 0.2;
double titleOffSetTwo = 0.8;
double mySpecialPaddingOne = 20;
int tabLength = 2;
double verySpecialPadding = 0;
int usefulZero = 0;
